### ISSUE TITLE
Deploy to dedicated namespace

### ISSUE THREAD

**Issue by mishraomp** [bcgov/pubcode#168]
now we have a dedicated namespace for this product, lets move our deployments to the dedicated namespace :).

@DerekRoberts , since they have changed the login process, please use Azure OIDC to see this new namespace.

**Comment by mishraomp** [comment]
I have modified and gave access to our github accounts, so now it is showing under github oidc

**Comment by DerekRoberts** [comment]
> I have modified and gave access to our github accounts, so now it is showing under github oidc

I'm looking forward to poking around that setup. :)
