### ISSUE TITLE
Not receiving all Renovate updates

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/pubcode#180]
Deployer action at minimum is behind.

**Comment by DerekRoberts** [comment]
Looks like Renovate is getting stuck on lockfile changes which are blocked by #165.  @mishraomp

**Comment by mishraomp** [comment]
I fixed the peer deps issue by lowering react to match the version and now we are at 17 than 18, in future we will address the issue of moving it to mui 5 and react latest version, but at this point we are free to use renovate again. @DerekRoberts

**Comment by DerekRoberts** [comment]
@mishraomp Great!  I'll get that back on track.  :)
