### ISSUE TITLE
Get The ministry list from BCDC using GHA

### ISSUE THREAD

**Issue by mishraomp** [bcgov/pubcode#238]
https://catalogue.data.gov.bc.ca/api/3/action/organization_list
https://catalogue.data.gov.bc.ca/api/3/action/organization_show?id=ministry-of-energy-mines-and-low-carbon-innovation

**Comment by mishraomp** [comment]
Fyi @annikaLiving , I will add you as a reviewer in the pr when I am ready.

cc @DerekRoberts

**Comment by annikaLiving** [comment]
Recommend using the GUIDs for the orgs. id will accept the id or the name.

https://catalogue.data.gov.bc.ca/api/3/action/organization_show?id=df6ab6f0-e025-4d7e-9792-861b90ccd554
